




server:
  port: 9000

spring:
  mail:
    host: smtp.qq.com
    username: 53643752@qq.com
    password: pmouprdjnqgacbad
    default-encoding: utf-8
    properties:
      main:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  application:
    name: USER
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tedu_store?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    type: com.zaxxer.hikari.HikariDataSource
mybatis:
  mapper-locations: classpath:mappers/*.xml

eureka:
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

oss:
  qiniu:
    domain: qlbwsydnk.hd-bkt.clouddn.com
    accessKey: Bs_qnGxtC-W4rzBTdOAC4GJppd4PvOF_XJcwkKhJ
    secretKey: I3e2-SH8gMVr2Z95F9uNfEPC0D0JZC50Doh9exaY
    bucketName: edu-sys